apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smarties
  labels:
    name: smarties
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: default
spec:
  rules:
  - host: real.encs.concordia.ca
    http:
      paths:
      - pathType: Prefix
        path: /chat(/|$)(.*)
        backend:
          service:
            name: chat-svc
            port: 
              number: 8080