apiVersion: v1
kind: Service
metadata:
  name: chat-svc
spec:
  type: LoadBalancer
  selector:
    app: chat
  ports:
  - port: 4040
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: airbenders/chat:latest
        resources:
          limits:
            memory: "1024Mi"
            cpu: "2000m"
        env:
        - name: CASSANDRA_CHAT_KEYSPACE
          value: chat
        - name: CASSANDRA_CHAT_TABLE
          value: messages
        - name: CASSANDRA_HOST
          value: "real.encs.concordia.ca:3000"
        - name: DB_HOST
          value: real.encs.concordia.ca
        - name: DB_PORT
          value: "3000"
        - name: AUTH_URL
          value: "http://auth-svc.default:3000/api/validate"
        - name: RABBIT_URL
          value: "amqp://guest:guest@real.encs.concordia.ca:8080/"
        ports:
        - containerPort: 4040