apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  type: LoadBalancer
  selector:
    app: auth
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: airbenders/auth
        resources:
        env:
        - name: DB_HOST
          value: postgres-svc
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: DB_PASSWORD
        - name: DB_NAME
          value: auth
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: SECRET_KEY
        ports:
        - containerPort: 3000
