apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - "ReadWriteOnce"
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: manual
  volumeName: postgres-pv
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
